### ISSUE TITLE
Removing the -pre suffix via command line parameteter

### ISSUE THREAD

**Issue by adrianvmsft** [AArnott/Nerdbank.GitVersioning#141]
It would be nice to be able to remove the -pre via a command line parameter.
This way you wouldn't have to commit a change to version.json just to create a one off package that removes -pre.

**Comment by AArnott** [comment]
Does the commit you're building produce a package with an API you're willing to commit to? If so, that commit should have a `version.json` file that reflects that by stripping the `-pre` suffix. Switching from an unstable to a stable package is a *big deal* -- not one to be trivially switched back and forth by way of a build flag. Someone looking at this commit later should be able to clearly tell that they're looking at "stable" code, and the commit that produced a package they already have. Build reproducibility is a big design goal for NB.GV so we treat flags that change version information without changes to this file with a lot of built-in resistance.

Besides, after shipping without the `-pre` flag, there's a pretty good chance folks will want to bump the version information anyway. So it's not like you'll get away with changing the version.json file for long. It's designed to be super easy to change, and only require changes when the version information needs to be changed by a human -- leaving all the automatable work for the build to work out.

**Comment by adrianvmsft** [comment]
I see your point, however I would argue that it depends on the release cadence and process.
In our case, we continuously produce -pre builds, until we are ready to ship a release package. Once we are ready, we typically kick off 1 build without -pre. After that we switch back to producing -pre builds.
Having to update version.json back and forth just for a build is a bit heavy weight.

On top of that we would like to use the same branch for 2 different purposes (to avoid the overhead of keeping 2 branches in sync):
- producing the binaries that get inserted into VS (and go through the shiproom approval process) and
- produce the packages that get shipped to nuget.
Currently making the version.json change would affect both, so we end-up having to create a separate branch just to accomodate the change to version.json.

**Comment by AArnott** [comment]
What is the difference in content between the two branches?

**Comment by adrianvmsft** [comment]
Very often it is just the removal of "-pre".

**Comment by AArnott** [comment]
What do you lose by removing it from "both" branches so you can maintain just one?

**Comment by adrianvmsft** [comment]
That is definitely possible, but it has some disatvantages:
- when we are ready to remove the "-pre" we are typically late in the release cycle so we would have to get approval just to remove "-pre"
- we need to make sure we remove -pre when we merge back to the branch for the next release

**Comment by AArnott** [comment]
Why not do this:
* remove it when your product is stable (but before it enters escrow). 
* add it back when you bump the version number and are unstable again.

The way I tend to do it is this:

1. code in `master` with `1.0-pre` in version.json
1. When it's time to stabilize for a release
   1. Branch off to a `v1.0` branch.
   1. Stabilize the branch
   1. Change version.json to just `1.0` in the v1.0 branch.
   1. Change version.json in `master` to `1.1-pre` or `2.0-pre` as appropriate.
1. Go through escrow and make changes to your code as necessary to prepare to ship. That wouldn't normally violate semver since you're already stable, just a little buggy. And even if you had to make breaking changes, you haven't published your package yet so it's not a violation.
1. Periodically merge `v1.0` to `master`. The first time you do this, you'll get a merge conflict in version.json because the file has diverged. Use the "KeepOurs" policy so that master keeps `2.0-pre`.
