### ISSUE TITLE
Use GitVersioning for TFS nuget packager task

### ISSUE THREAD

**Issue by Tobias-Gr** [AArnott/Nerdbank.GitVersioning#188]
Hi,
we have a TFS build definition that creates a nuget package from a few javascript files (created by npm build) via nuget packager task. In the past we used GitVersion-Commandline for generating the version and then used the GitVersion-EnvVar to pass the version to the nuget packager via nuget arguments field. 
How can the same be achieved with GitVersioning? Does the npm/gulp-approach (https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/gulp.md ) set EnvVars like the msbuild-approach does?

Thanks!
Tobias

**Comment by AArnott** [comment]
IIRC neither msbuild nor npm tasks in this project set environment variables. The msbuild one sets msbuild properties and/or communicates by various means to the cloud build server (when applicable and activated). I don't expect that should be a blocker for you though, since if you need environment variables to be set you can surely set them yourself.

We do have a pair of scripts in the NB.GV nuget package under the tools folder. One is called `Get-Version.ps1` which returns a powershell object with all the version information. You can strip it down to just returning the NuGet package version, from cmd.exe, with such a command as this:

```cmd
powershell -c (c:\Users\andarno\.nuget\packages\nerdbank.gitversioning\2.1.23\tools\Get-Version.ps1).nugetpackageversion
```

Also note that #181 may be useful to you when that is done.

**Comment by Tobias-Gr** [comment]
Works perfectly, thanks!
