### ISSUE TITLE
Add support for CentOS

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#219]
As @bording points out in https://github.com/AArnott/Nerdbank.GitVersioning/pull/218#discussion_r212806977, we should update to libgit2sharp 0.26.0, including taking care to load the right native libgit2 library based on RID at runtime so that NB.GV works on more Linux platforms including CentOS.

**Comment by bording** [comment]
If the plan to remove the OpenSSL and curl dependencies from the native libraries works the way I'm thinking it will, then the work to handle this will be simplified.

My current thinking is that instead of the handful of different RIDs we have in the current 0.26.0 preview, we'd just need two different linux libraries, one for musl libc distros (alpine) and one for everything else.

**Comment by shawnallen85** [comment]
Any update on this?

**Comment by AArnott** [comment]
@bording do you have an issue tracking CentOS support on the libgit2sharp side? 
Now that with #244 we support the RID loading for various *nix platforms, I think we can support CentOS as soon as libgit2sharp does.
