### ISSUE TITLE
Cake alias doesn't work

### ISSUE THREAD

**Issue by Cheesebaron** [AArnott/Nerdbank.GitVersioning#225]
When adding the the addin:

```csharp
#addin Cake.GitVersioning
```

Then calling `GetVersioningGetVersion()` in your cake build script. When attempting to run the script it fails with:

```
Error: Error(s) occurred when compiling build script:
C:/git/AppCore/build.cake(24,1): error CS0103: The name 'GetVersioningGetVersion' does not exist in the current context
```

I see the addin is added in the tools folder. However, it appears like it isn't referenced for some reason.

I am trying this with Cake version 0.30.0

Cake also complains about Cake.GitVersioning is referencing an old version of cake:

```
The assembly 'Cake.GitVersioning, Version=2.2.13.4404, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.0).
For best compatibility it should target Cake.Core version 0.28.0.
```

**Comment by AArnott** [comment]
@clcrutch Can you help with this?

**Comment by clcrutch** [comment]
@Cheesebaron It turns out their was a typo in the documentation.  The proper alias is `GitVersioningGetVersion` instead of `GetVersioningGetVersion`.  I've submitted a PR to address the typo.

@AArnott As far as the warning about the newer version of Cake, I'll submit an additional PR to address the Cake version mismatch.
