### ISSUE TITLE
 Major, Minor and Patch version parts as separate variables

### ISSUE THREAD

**Issue by petersendev** [AArnott/Nerdbank.GitVersioning#233]
Hi, additionally to the NBGV_MajorMinorVersion I would really like to have all the version parts available as separate (environment) variables.

Since (as I understand it) the version height doesn't have to be in the patch part of the version, all three would be preferable.

I need this primarily in a cloudbuild (via _nbgv cloud -c -a_) for docker tags ( 0.x, 0.1.x, 0.1.2), which is currently not possible without parsing the version via script.

I would like to request the feature that nbgv would set NBGV_Major, NBGV_Minor and NBGV_Patch.

As a bonus, the NBGV_PrereleaseVersion without the leading dash would also be welcomed.

**Comment by AArnott** [comment]
This all sounds reasonable. I'll try to get this done over the next week or so. But anyone else is welcome to send a PR as well.

**Comment by AArnott** [comment]
The properties (excluding the `NBGV_` prefix) are:

1. `VersionMajor`
1. `VersionMinor`
1. `BuildNumber` (this was preexisting)
1. `VersionRevision`

The `BuildNumber` always represents the 3rd integer in the version. If you want the version/git height specifically, use `VersionHeight`, since as you say that *may* not appear as the 3rd integer.

I've also added a `PrereleaseVersionNoLeadingHyphen` property for you.

**Comment by petersendev** [comment]
Sounds great, thank you so much!

**Comment by petersendev** [comment]
Any ETA on a release? Would love to migrate my last projects, but they are blocked by this.
