### ISSUE TITLE
required permissions to set a build number on Azure Pipeline

### ISSUE THREAD

**Issue by josesimoes** [AArnott/Nerdbank.GitVersioning#247]
Hi,

I'm getting this error in Azure pipelines when executing `nbgv cloud`.

`The user 'guid-guid-guid' is not authorized to access this resource.`

This build was triggered by a commit to a PR. Any idea what is causing this?

BTW: awesome work with this project! 👏

**Comment by AArnott** [comment]
Was the PR from a fork of the repo? Azure Pipelines doesn't yet support setting build numbers (or publishing artifacts) in PR builds when the source branch in the PR comes from a fork of the receiving repo. So you have to disable setting the cloud build number for fork builds.

To do this, change your version.json file to *not* set the cloud build number. Then add this to your YML file (or equivalent in your UI-based build definition) so that the build number is still set for all your non-fork builds:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/b88a7420e7fc225259fc52c6df47cf9de7592a2b/azure-pipelines.yml#L31-L35

**Comment by josesimoes** [comment]
Hum... the branch from the PR originated is from a fork, no doubt about that.

A curious fact is that if I queue the build from the Azure portal UI it goes through that same step smoothly and sets the build fine. Please check the logs [here](https://dev.azure.com/nanoframework/nanoFramework.Networking.Sntp/_build?definitionId=1).

**Comment by AArnott** [comment]
I can only explain that by saying an explicitly queued build is considered by Azure Pipelines an implicit endorsement that it's safe to complete all steps.
