### ISSUE TITLE
Get-Version.ps1 doesn't work in 2.2.13

### ISSUE THREAD

**Issue by the-ress** [AArnott/Nerdbank.GitVersioning#248]
`Get-Version.ps1` fails with:
```
Exception calling "HelpFindLibGit2NativeBinaries" with "1" argument(s):
"Unable to find native binaries under directory: "[...]\NerdBank.GitVersioning\tools\..\build\MSBuildFull\lib\win32\x64"."
```

It seems 2.2.13 moved the lib directory (0da2e40006b55b07c7de7a5721e9ea222d393d68), but the script wasn't updated.

**Comment by AArnott** [comment]
Thanks for the report. I haven't been testing the .ps1 scripts lately now that we have the `nbgv` dotnet CLI tool. Does that work for you?

**Comment by AArnott** [comment]
True. That does make the .ps1 a bit more convenient. However you can use nbgv for that purpose as well: 

```ps1
nbgv get-version -f json | ConvertFrom-Json
```

And voila! You have a powershell object again. :)

**Comment by heaths** [comment]
The problem is that `nbgv get-version` returns the wrong information. For example, it shows the build version as 3.2.0.37 while `get-version.ps1` correctly shows 3.2.37.

**Comment by AArnott** [comment]
That's interesting. the ps1 script and the nbgv tool use exactly the same `VersionOracle` class to get the answers. I wonder if it's just a formatting thing. 
FWIW, the `version` property in your `version.json` file looks misleading: it has a 3rd integer set to zero, but I think NB.GV ignores that. But it might be enough to throw off the `nbgv` tool and if so, is probably why I didn't catch it, since I'm not testing with inert trailing `.0` in my `version` property. @heaths if you wouldn't mind sharing your repo info with me, I can try it out.

**Comment by heaths** [comment]
I tried removing the ".0" and get the same result. See the develop branch of https://github.com/heaths/psmsi repo. Happens on an internal repo as well.

**Comment by AArnott** [comment]
I guess the trailing `.0` isn't ignored any more anyway. NB.GV used to ignore that, but now it just moves height integer to the 4th position. Sorry I forgot about that.

Anyway, I can repro the .ps1 script failure, and also some inconsistencies in reporting versions by the various build/script/tools. So I'm working on that now.

**Comment by AArnott** [comment]
@heaths I tried commit a4b68111a on your repo (since your develop branch moved on since your report, evidently) and both nbgv and get-version.ps1 (after #258 and #256) report your version as 3.2.0.37, which given your version.json contains "3.2.0" appears to be the corrrect version.

> For example, it shows the build version as 3.2.0.37 while get-version.ps1 correctly shows 3.2.37.

Why do you say 3.2.37 is the correct value when your version.json calls for "3.2.0" as the first three integers?

**Comment by AArnott** [comment]
Yes, in some cases at least, committing the version.json file is required.
