### ISSUE TITLE
Performance of GetBuildVersion task

### ISSUE THREAD

**Issue by azeno** [AArnott/Nerdbank.GitVersioning#31]
Is there anyway to improve the performance of the GetBuildVersion task? 
In my case I've a solution with about 30 projects all in the same git repository and all of them get the same version in the end. The git repository is rather large, containing more than 20.000 commits. When doing a full rebuild each invocation of GetBuildVersion takes about one second summing up to a total of about half a minute additional build time. When doing an incremental build it's usually about 5 to 10 projects which are affected adding additional 5 to 10 seconds build time which kinda hurts.
Since all of these invocations of GetBuildVersion return the same results in the end I was wondering whether or not this can be improved.

In any case thank you for this project in combination with NuProj, something I've been looking for a long time now.

**Comment by AArnott** [comment]
This is great feedback. Thanks. Yes, I can think of some ways we can improve this.

**Comment by AArnott** [comment]
I'm working on this now, but it would be very helpful if you could collect perf traces of your build so that I can be sure I'm making the changes that will speed up your build. Can you please use [PerfView](http://www.microsoft.com/en-us/download/details.aspx?id=28567) to collect those traces? 
After downloading it:

1. click Collect-> Collect (it may restart to elevate, then repeat this step)
1. Check the 'Zip' option
1. Expand "Advanced Options"
1. Check the "No V3.X NGEN Symbols" option
1. Make sure Current Dir and Data File are set to where you want to place the trace file(s).
1. Prepare to kick off a build that will demonstrate the problem. Arrange for the build you're measuring to last 10-20 seconds (by picking which projects to build, or using an incremental build).
1. Click Start Collection, and immediately kick off your build.
1. When your build is done, stop collection in PerfView.
1. It could take 30 seconds or even minutes to wrap up its work. Then send me the .zip file it creates.

This will give a very clear and reliable picture of where the time in your build goes, and in particular, I can look at the GetBuildVersion task time to make sure that all the expensive operations get saved and reused across all projects in the future.

**Comment by azeno** [comment]
I've added two traces. The AffectedAllProjects was a solution build (not re-build) which touched all 38 projects. The AffectedFiveProjects was after I changed one line of code and did a build of the top-level project file.

http://we.tl/EC5EKmHNuE

**Comment by AArnott** [comment]
Thanks. I'm taking a look now.

**Comment by AArnott** [comment]
@azeno: can you please try this fix to see if it helps your build?

NuGet package source: https://ci.appveyor.com/nuget/nerdbank-gitversioning
Version to upgrade to: 1.1.56-rc-gcfa44ca7d1

**Comment by azeno** [comment]
Works like a charm! Thank you!
