### ISSUE TITLE
AssemblyVersion only set for compile not restore

### ISSUE THREAD

**Issue by r-bennett** [AArnott/Nerdbank.GitVersioning#351]
If I have an application `A` with a `ProjectReference` to some assembly `B` versioned using `Nerdbank.GitVersioning`, the generated code in `B` sets `AssemblyVersionAttribute` and friends but these are only visible at compile-time and not at restore-time (restore instead always sees `B`'s version as `1.0.0`, and this is the version that is written in to the `A`'s `project.assets.json`).

Is there a way to set the version correctly for the NuGet restore (as it is if we specify `<VersionPrefix>` directly in `B`'s csproj instead of using `GitVersioning`)?

Some context for why this is a problem - we currently use source dependencies for almost all of our internal code, and are in the process of migrating to binary dependencies (with the help of `GitVersioning` for controlling our package versions). As such, during the transition period we are likely to have dependency trees with both `ProjectReferences` and `PackageReferences` to the same assemblies. In this case in a NuGet restore the version of the `ProjectReference` seems to take precedence over the version of the `PackageReference`, regardless of which is closer to the application in the dependency tree. Since this version is `1.0.0`, this leads to version conflicts and build failures if the `PackageReference` version is > `1.0.0`.

This is fairly easily resolved by adding a direct (rather than transitive) `PackageReference` from the application to the offending dependency, but I can imagine there are other potentially negative effects of NuGet seeing the wrong version during restore that I haven't come across yet.

**Comment by AArnott** [comment]
Interesting problem. Can you do a little research to see if something like this would solve your problem?

Figure out which msbuild targets run in project `B` during a restore, and then add this target to `B.csproj`:

```xml
<Target Name="FixVersionForRestore" 
       AfterTargets="NuGetRestore-Or-Whatever-Its-Called"
       DependsOnTargets="GetBuildVersion" />
```

That said, I don't think this will work (at least, not all the time). The problem is you have a chicken-and-egg problem in that NB.GV itself is restored during restore. So MSBuild evaluates B.csproj, the restore targets are run, which brings down NB.GV (possibly for the first time on the box), and only *then* does the `GetBuildVersion` target even exist, and not for that project evaluation since it already occurred. 

This is the same chicken and egg problem that led us to similar issues to nuget:

https://github.com/NuGet/Home/issues/6536
https://github.com/NuGet/Home/issues/4790

**Comment by r-bennett** [comment]
Cheers for the info - I see why this is a bit of a problem. I'm about to disappear off-grid for a couple of weeks, but I should be able to have an experiment with this when I'm back.

**Comment by AArnott** [comment]
alright. Let me know if you think of something that works.
