### ISSUE TITLE
Do not update version in package-lock.json

### ISSUE THREAD

**Issue by heaths** [AArnott/Nerdbank.GitVersioning#390]
Based on recommendations for pipeline caching at https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops#nodejsnpm, NBGV shouyld not stamp the version in package-lock.json. I talked with our JavaScript partners for Azure SDK and they can't think of a valid scenario why you'd need to update package-lock.json anyway.

I'm aware of the workaround instructions to copy all files, but - especially for large projects with many files - that seems like overkill. And some tools like vsce (the VSCode extension utility) don't appear to let you re-base a package (maybe it's just a matter of setting the working dir, but that kinda proves my point: there's lots of "fixes" everyone would have to do with this workaround).

Seems it'd be best for everyone if package-lock.json just wasn't touched at all. Let npm manage that. Same would go for yarn if you update its lock file as well.

I'd be happy to make a fix if you agree.

**Comment by AArnott** [comment]
I'm not sure what you're talking about, since nbgv doesn't ever write to package-lock.json. Not directly, anyway. All we do is:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/6b0a602909dcba13279e73e3c74f6e5f8ec57b6d/src/nerdbank-gitversioning.npm/ts/index.ts#L73

And I'd *love* to avoid touching files at all, but I don't know how to convince NPM to build a package with any version other than what is hard-coded in the package.json file, so my intent was to stamp the package.json file's version, and I use the `npm` tool to do that.

**Comment by heaths** [comment]
Good to know. To be honest, I hadn't dug into it yet. So it seems npm is doing it and I can explore more there. But you'd be fine with avoiding modifying the lock file then?

**Comment by AArnott** [comment]
All I care about is that `npm pack` will use the applied version. If that doesn't require changing `package-lock.json`, and avoiding that solves a problem for you, yes I'll take a PR.

**Comment by heaths** [comment]
Looking into this more, I think it's probably just best to document an example similar to what I [used](https://github.com/heaths/vscode-guid/blob/b18504907cca3288bf9e02125dfbefbdd793594f/gulpfile.js#L53-L68). There's a lot of ways people might do this, what lockfiles they use along with what package managers (e.g. npm vs. yarn), so probably just documenting it would be best,  yeah?
