### ISSUE TITLE
[Question] Prerelease labels based on branch?

### ISSUE THREAD

**Issue by hypervtechnics** [AArnott/Nerdbank.GitVersioning#402]
Hi,

sorry to post here, but Gitter seems dead. I have a question:

Is it possible to make the version automatically contain a specific prerelease label based on the current branch?

I am meaning e.g. the following:

master or release/v* => `no prerelease tag`
develop => `beta`
feature/* or any other => `alpha`

Or am I missing a concept here or misunderstanding the usage?

Greetings

PS: _Small_ ;) question: How complex would you think auto-generating a changelog based on the commit messages between the version changes? So a changelog since last change in major, minor, build and revision version parts...

**Comment by AArnott** [comment]
> Gitter seems dead. 

I don't see any comment from you on [our gitter channel](https://gitter.im/AArnott/Nerdbank.GitVersioning). And the last comment there is from me. Don't assume it's dead just because I've answered every question on that forum more recently than the most recent question. :)

> Is it possible to make the version automatically contain a specific prerelease label based on the current branch?

Yes, but I'm pretty firmly not going to do it. Branches are mutable in git, and a firm principle with NB.GV is that the generated versions are stable. A single commit could belong to any number of branches, and that set of branches could change over time. 

Instead, we have the `nbgv prepare-release` command that will allow you to branch off a stable/servicing branch that advances the prerelease tag to the next stable thing in a list you define (IIRC). 

Becoming (more) stable is a choice that IMO the owner of the package should make based on the quality of the code at a given commit. And that merits a change to `version.json` so that everyone knows for all time that you felt a commit was beta quality instead of alpha quality. Instead if branch names were used, a few months or years down the road when all those branches are merged and gone, it becomes extremely difficult for you to determine whether a given commit was developed and/or released as a beta, rc, or even a stable package.

**Comment by AArnott** [comment]
> How complex would you think auto-generating a changelog based on the commit messages between the version changes? So a changelog since last change in major, minor, build and revision version parts...

I'm not sure what that has to do with package/file versioning. I understand that some folks have crafted conventions for formatting git commit comments so that changelogs could be automatically produced. I haven't paid them much attention however.

**Comment by hypervtechnics** [comment]
First: Thank you very much for your explanation and answer! 😃
For the gitter: As the last message was from May I assumed (incorrectly) that it was dead...

> Yes, but I'm pretty firmly not going to do it.

What I understand: This is a design choice to keep up with the flexibility/durability of the git branches. Again thank you for explaining why and what approach you took to work with this.

So there if I wanted alpha => beta => release (no prelease) I would need to do the following branching:

```
1. `master`, `develop` (Start)
2. `feature/new-feature`, `master`, `develop` (feature branch has `alpha` pre release label set in version.json after branch created manually)
3. ... feature being developed
4. `feature/new-feature` being merged into `develop` (`beta` pre release label set in version.json in feature branch before merging)
5. `develop` being built as `beta`
6. Using `nbgv prepare-release` to create branch e.g. `release/v1.4`
7. ... `release/v1.4` building as version `1.4-beta` and bug fixes to this branch
8. `release/v1.4` being stable after bug fixing
9. `release/v1.4` being merged into `master` (pre release removed in version.json in release branch before merging)
10. `master` being built as `1.4` and can be deployed and so on
11. Merging `master` back in to `develop` (here the version.json needs to be changed after the merge to keep the master branch clean from pre release labels) (this seems problematic to me as it causes incosistencies in the develop branch regarding the beta prl)
```

Am I getting this right? Seems a lot of manual work and the version increment would need to be done at the start of the development so that the pre release tag make sense. I could not find an example work flow for having both alpha and beta. How I am supposed to handle beta in the release branch is clear to me. Ensuring the appropiate pre release tags in the merge request is also quite easy as adding a new "pipeline" to check the required pre-release label for the branch.

>  that advances the prerelease tag to the next stable thing in a list you define (IIRC).

For the list: Can I define it in a written way? Saying that the order is alpha => beta => release. Or do devs have to do it "manually"? Just wanting to prevent issues here.



> I'm not sure what that has to do with package/file versioning.

Nothing 😆 Just wanted to know how you think about that. I am planning to automate a lot of steps during development so that you can focus on developing while maintaining a good changelog, update mechanism, versioning, etc via CI/CD... 

Generating changes since last major/minor release is quite easy as just checking when version.json experienced the last change and comparing the version. As entries I can either take the commit messages or descriptions and/or only merge commits and their description on develop/master branches. (This only as a note.)
