### ISSUE TITLE
More control over prelease tag

### ISSUE THREAD

**Issue by azeno** [AArnott/Nerdbank.GitVersioning#412]
This is more of a question first and if not possible can be considered a suggestion.

I've the following setup in my version.json file in my development branch:
```
{
  "version": "2019.1.0-{height}",
  "publicReleaseRefSpec": [
  	"^refs/heads/master$" // drop GitCommitId in master branches
  ],
}
```
The generated version is "2019.1.0-1234-GitCommitId" - so far so good. The idea is that our prerelease packages have a nice ordering, also height is internally used to apply converters on certain documents. When we merge back to master we manually need to adjust the version part by removing the -{height} part and commit again on master in order to get a stable version out of it -> "2019.1.0".
This causes merge conflicts between master and development branches later on - which are of course solvable but (here it comes) what would be very nice if GitVersioning would drop the entire prerelease part on its own and not just the GitCommitId.

Is that possible somehow already and I simply overlooked it in the docs or if not any chance that's doable? Or are there strong reasons against such a feature?

Thanks and keep up the good work!

**Comment by AArnott** [comment]
It sounds like you want to add/remove the prerelease suffix based on the branch name or perhaps some environmental setting rather than what's in that commit. If so, it sounds very similar to #290. Can you read over that and let me know if you agree?

It's not a feature I'm inclined to do, since IMO "stable" is something that's "baked in" to the source code and is worthy of a commit to mark that point in development, rather than a convenient switch you flip on and off at will for the same commit. I'm curious why you find that useful. But we can have that conversation over on the other issue if you agree it's asking for the same thing.

**Comment by azeno** [comment]
Hm I must admit I can't really follow the other proposal. What I had in mind was simply dropping the whole prerelease part from the version scheme when building on the main branch. But maybe you're right and it's better to do that actual commit on the main branch where one cleary has to set the version by hand instead of relying on some switching mechanism.

**Comment by AArnott** [comment]
Thanks.
