### ISSUE TITLE
nbgv prepare-release "Uncommited changes in directory"

### ISSUE THREAD

**Issue by ssa3512** [AArnott/Nerdbank.GitVersioning#439]
I am attempting to evaluate use of the Nerdbank.GitVersioning package and tools and I am getting a message "Uncommited changes in directory" when trying to run nbgv prepare-release.

git status shows no changes.

![image](https://user-images.githubusercontent.com/1991399/75355141-06b5fb00-587c-11ea-9aed-e83d6c4a1a18.png)

**Comment by AArnott** [comment]
Hmmm... What version of nbgv are you using?

**Comment by ssa3512** [comment]
3.0.50; just installed it this morning using `dotnet tool install -g nbgv`

**Comment by AArnott** [comment]
Strange. It works for me. But libgit2sharp (which we use underneath) did recently introduce a temporary file issue where it makes the working copy dirty. But IIRC I upgraded to apply their fix and I haven't seen the problem since.
I wonder if you could use a managed debugger to launch nbgv so you can break/pause the process when the exception is thrown, then run `git status` on the directory to see if anything is dirty.

**Comment by ssa3512** [comment]
I stepped through and it looks like something went wrong with line endings - there were two csproj files showing changes in repository.RetrieveStatus().Modified. I opened them, added a space, saved, removed the space and saved again and then committed. This did NOT create a commit, but now repository.RetrieveStatus().IsDirty is false and nbgv prepare-release is working.
