### ISSUE TITLE
Get branch name / last component for use in metadata

### ISSUE THREAD

**Issue by heaths** [AArnott/Nerdbank.GitVersioning#82]
We like to distinguish one-off builds by including the branch name (sometimes just the last component of a develop topic branch) in the metadata of the package. It would be great if we could get this information from the build task and use it as part of the version for both binaries and nuget/npm packages.

**Comment by heaths** [comment]
I see from https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/NerdBank.GitVersioning/VersionOracle.cs#L61 that a supported cloud service can pass in the branch name but this, of course, does not work on local builds. The nearest branch (or even just the one branch based on the commit) could be used, but exposing the aforementioned line could be a good start.

**Comment by AArnott** [comment]
If you want build versions to include branch names, then you might want to look at [GitVersion](https://github.com/GitTools/GitVersion) instead. One of the main distinguishers between this and that project is that GitVersion stamps build versions with branch names and this doesn't. That's by design for this project, since a primary goal of this project is reliable reproducibility, and the branch name can be any value for a given commit and can change over time. 

The `VersionOracle` functionality you refer to isn't for stamping branch names into versions, but rather for recognizing whether it's a 'release' branch for purposes of stripping the git commit ID from the package version string. 

If I'm missing something, please feel free to follow-up.

**Comment by heaths** [comment]
I'm using GitVersion for another project, and really don't like that it stamps versions which is why 1) we're using this internally, and 2) I'm probably going to be switching my personal projects to this. Getting GitVersion working happily with my GitFlow (really, no different than normal) and AppVeyor has been a pain.

I understand that the code snippet is for identifying release branches, but seems it wouldn't be a stretch to just get the name. Mainly, some of our developers would like to queue a build in VSTS to get a NuGet package to test their changes. We don't build them in PRs. This allows us to easily identify which packages are for that purpose. But, yes, there's other ways to solve this (and I have) so if you don't think it's generally useful, that's cool.

**Comment by AArnott** [comment]
What if I set an MSBuild property during the build to the branch name, then I leave it as an exercise to the reader to add that branch name to the buildMetadata MSBuild item list so you can do what you want?

**Comment by heaths** [comment]
Sounds good. But what is this item group of which you speak? Is that for nuproj files? If it can handle harvesting project output and metadata (description, copyright, etc.) and work with our signing process it may be worth it.

**Comment by AArnott** [comment]
It's the [`BuildMetadata` item list](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/Nerdbank.GitVersioning.NuGet/build/NerdBank.GitVersioning.targets#L45). You can add items of this type so that it automatically gets concatenated to version strings.

**Comment by TFTomSun** [comment]
@AArnott has that msbuild property for the branch name already been added? Unfortunately the link above is dead. Can you explain a bit more how the build meta item list is used for the version specification?

**Comment by AArnott** [comment]
I've fixed the link. The `BuildMetadata` is _not_ a property. It's an item type. So you could add build metadata with such syntax as this:

```xml
<ItemGroup>
  <BuildMetadata Include="master" />
</ItemGroup>
```

**Comment by TFTomSun** [comment]
> What if I set an MSBuild property during the build to the branch name, then I leave it as an exercise to the reader to add that branch name to the buildMetadata MSBuild item list so you can do what you want?

@AArnott I was talking about the property you mentioned here. I thought you have already code that can determine the branch name based on the  clone git repo and you just needed to expose it to msbuild as a property so that we can use it in the build meta to add it to our version specification.

**Comment by AArnott** [comment]
@TFTomSun  NB.GV doesn't expose the branch name. But most cloud build servers do, via environment variables.

**Comment by TFTomSun** [comment]
@AArnott  I see, but then I won't be able to create the same package name when I do a local built, right?

**Comment by AArnott** [comment]
Ya. NB.GV very much prioritizes getting the same package version wherever it may be built. That's why we don't use branch names in version specifiers. A given commit may be a part of any number of branches, and that set of branches can change over time. We only distinguish whether a package was built from one of the 'public release' branches for purposes of simplifying the version.
