### ISSUE TITLE
Semver 2.0 metadata fails "nuget pack" with referenced projects

### ISSUE THREAD

**Issue by heaths** [AArnott/Nerdbank.GitVersioning#83]
While `$(NuGetPackageVersion)` replaces the "+" with "-" and allows `nuget pack` to succeed, if you use `-IncludeReferencedProjects` nuget because the `AssemblyInformationalVersionAttribute` value is invalid.

What might be nice is to allow (opt-in, to avoid breaking compat) semver 1.0 versions. We were able to work around this by hooking in our own target, but others may run into this as well.

**Comment by AArnott** [comment]
Can you provide more information about the error you're hitting? `AssemblyInformationalVersionAttribute` can be anything you like. If NuGet is failing because it can't parse it, please file a bug against NuGet.

The `NuGetPackageVersion` property *is* semver 1.0. At least by my understanding it is. Why do you say it is not?

**Comment by AArnott** [comment]
BTW, it sounds like you're not using NuProj. Have you considered using that for your nuget packaging needs?

**Comment by heaths** [comment]
It's the "+" after the first metadata and before the short commit id. NuGet doesn't completely support it (known issue, mainly because of back-compat issues and mixed binary versions).

**Comment by AArnott** [comment]
The `NuGetPackageVersion` property doesn't have a `+` sign in it. That character is changed to a `-` character in that property so that NuGet can consume it. `AssemblyInformationalVersionAttribute` retains the `+` character because any string is allowed in that attribute.
Is the `-IncludeReferencedProjects` switch causing NuGet to try to parse the string passed to the `AssemblyInformationalVersionAttribute`?

**Comment by heaths** [comment]
Yes, it parses that attribute.






On Wed, Jul 13, 2016 at 1:23 PM -0700, "Andrew Arnott" <notifications@github.com> wrote:





The `NuGetPackageVersion` property doesn't have a `+` sign in it. That character is changed to a `-` character in that property so that NuGet can consume it. `AssemblyInformationalVersionAttribute` retains the `+` character because any string is allowed in that attribute.
Is the `-IncludeReferencedProjects` switch causing NuGet to try to parse the string passed to the `AssemblyInformationalVersionAttribute`?

---

**Comment by AArnott** [comment]
Can you please provide repro steps and/or file a bug against the nuget team?

**Comment by heaths** [comment]
Outdated.
