### ISSUE TITLE
Feature request: Allow "major" as one of the values for assemblyVersion.precision

### ISSUE THREAD

**Issue by asherber** [AArnott/Nerdbank.GitVersioning#96]
I'd like to be able to have my `AssemblyVersion` only pick up the major part of the `AssemblyFileVersion`. (Why? See https://codingforsmarties.wordpress.com/2016/01/21/how-to-version-assemblies-destined-for-nuget/)

I think this might be as simple as adding `Major` to the `VersionPrecision` enum and then tweaking `VersionOracle.GetAssemblyVersion` (and adding major to `version.schema.json`).

**Comment by AArnott** [comment]
Agreed. I have no objection to enabling this. I may not get to it in the next few days so if you're interested (as you seem to have already reviewed the necessary changes) and want to send a PR, I'd be happy to review and accept it.

**Comment by AArnott** [comment]
BTW, for what it's worth, I believe major.minor is a better assembly version than just major. The reason is I'd rather see an exception stating it couldn't find version 3.4 of my assembly than an exception saying it couldn't find a particular method. Since semver would suggest (or at least the way I interpret it) that new API warrants a bump to the minor version number, any new features will require a newer assembly version, it guarantees a useful exception. And binding redirects (which NuGet and MSBuild both automatically generate as necessary nowadays) take care of making sure that if I compiled against 3.2, it will still run against 3.3 (but not 3.1) which is exactly the behavior I want. But if I only can compile against 3.0 (because minor version is always zero) then there's no documentation or runtime enforcement that I actually get at least version 3.2.

**Comment by asherber** [comment]
Thanks much for the response. I don't disagree with your analysis – I'm still finding my way around what works best – but I have had good results with the method outlined in that article, and I think it's worthwhile to have that option.

PR has been submitted.
